"""empty message

Revision ID: 09927b467369
Revises: dd0beb1fd948
Create Date: 2021-08-14 16:09:28.915182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09927b467369'
down_revision = 'dd0beb1fd948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userfeature',
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('HumanFeature_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['HumanFeature_id'], ['human_feature.id'], name=op.f('fk_userfeature_HumanFeature_id_human_feature')),
    sa.ForeignKeyConstraint(['User_id'], ['user.id'], name=op.f('fk_userfeature_User_id_user')),
    sa.PrimaryKeyConstraint('User_id', 'HumanFeature_id', name=op.f('pk_userfeature'))
    )
    op.drop_table('User')
    op.add_column('user', sa.Column('department_id', sa.Integer(), nullable=False))
    op.drop_constraint('fk_user_deoartment_id_department', 'user', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_department_id_department'), 'user', 'department', ['department_id'], ['id'])
    op.drop_column('user', 'deoartment_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('deoartment_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_user_department_id_department'), 'user', type_='foreignkey')
    op.create_foreign_key('fk_user_deoartment_id_department', 'user', 'department', ['deoartment_id'], ['id'])
    op.drop_column('user', 'department_id')
    op.create_table('User',
    sa.Column('User_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('HumanFeature_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['HumanFeature_id'], ['human_feature.id'], name='fk_User_HumanFeature_id_human_feature'),
    sa.ForeignKeyConstraint(['User_id'], ['user.id'], name='fk_User_User_id_user'),
    sa.PrimaryKeyConstraint('User_id', 'HumanFeature_id', name='pk_User')
    )
    op.drop_table('userfeature')
    # ### end Alembic commands ###
