"""Initial joins

Revision ID: 0ffd1516f247
Revises: 
Create Date: 2021-08-13 18:47:46.369270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ffd1516f247'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_department'))
    )
    op.create_table('human_feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_human_feature'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('cit', sa.String(length=80), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('personal_no', sa.Integer(), nullable=False),
    sa.Column('birth_of_date', sa.DateTime(), nullable=False),
    sa.Column('date_of_exspiry', sa.DateTime(), nullable=False),
    sa.Column('card_no', sa.String(length=10), nullable=False),
    sa.Column('signature', sa.String(length=180), nullable=False),
    sa.Column('place_of_birth', sa.String(length=100), nullable=False),
    sa.Column('date_of_issue', sa.DateTime(), nullable=False),
    sa.Column('issuing_autority', sa.String(length=100), nullable=False),
    sa.Column('profile', sa.String(length=180), nullable=False),
    sa.Column('date_crated', sa.DateTime(), nullable=False),
    sa.Column('deoartment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deoartment_id'], ['department.id'], name=op.f('fk_user_deoartment_id_department')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('personal_no', name=op.f('uq_user_personal_no'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('human_feature')
    op.drop_table('department')
    # ### end Alembic commands ###
