"""empty message

Revision ID: dd0beb1fd948
Revises: 0ffd1516f247
Create Date: 2021-08-13 19:48:55.780501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd0beb1fd948'
down_revision = '0ffd1516f247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('HumanFeature_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['HumanFeature_id'], ['human_feature.id'], name=op.f('fk_User_HumanFeature_id_human_feature')),
    sa.ForeignKeyConstraint(['User_id'], ['user.id'], name=op.f('fk_User_User_id_user')),
    sa.PrimaryKeyConstraint('User_id', 'HumanFeature_id', name=op.f('pk_User'))
    )
    op.create_unique_constraint(op.f('uq_department_department'), 'department', ['department'])
    op.create_unique_constraint(op.f('uq_human_feature_feature'), 'human_feature', ['feature'])
    op.create_unique_constraint(op.f('uq_user_card_no'), 'user', ['card_no'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_card_no'), 'user', type_='unique')
    op.drop_constraint(op.f('uq_human_feature_feature'), 'human_feature', type_='unique')
    op.drop_constraint(op.f('uq_department_department'), 'department', type_='unique')
    op.drop_table('User')
    # ### end Alembic commands ###
